# Generated by Django 4.2.9 on 2025-05-13 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("layers", "0044_alter_dataset_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDataset",
            fields=[
                (
                    "dataset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="layers.dataset",
                    ),
                ),
                (
                    "long_descritption",
                    models.TextField(verbose_name="Long Description"),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("layers.dataset",),
        ),
    ]
